# Generated by Django 5.1.7 on 2025-03-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narcise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cathegorie',
            field=models.CharField(default='science', max_length=20),
        ),
    ]
